name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name adn-cli adn/__main__.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adn-cli-windows
        path: dist/adn-cli.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name adn-cli adn/__main__.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: adn-cli-linux
        path: dist/adn-cli

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: adn-cli-windows
        path: ./windows/
    
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: adn-cli-linux
        path: ./linux/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./windows/adn-cli.exe
          ./linux/adn-cli
        body: |
          ## ADN CLI ${{ github.ref_name }}
          
          ### 📥 Instalación rápida
          
          **Windows:**
          1. Descarga `adn-cli.exe`
          2. ¡Listo para usar!
          
          **Linux:**
          1. Descarga `adn-cli`
          2. `chmod +x adn-cli`
          3. `./adn-cli --help`
          
          **Python (cualquier SO):**
          ```bash
          pip install adn-cli
          ```
          
          ### 🚀 Uso rápido
          ```bash
          adn config init
          adn create --all
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}